import { StyleSheet } from 'react-native';

import { colors } from '../../theme';

export const styles = StyleSheet.create({
  content: {
    alignSelf: 'center',
    backgroundColor: colors.surface.app,
    gap: 0,
    maxWidth: 760,
    padding: 16,
    paddingBottom: 32,
    width: '100%',
  },
  emptyBox: {
    alignItems: 'center',
    backgroundColor: colors.surface.card,
    borderColor: colors.border.default,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 4,
    padding: 28,
  },
  emptyText: {
    color: colors.text.tertiary,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
    textAlign: 'center',
  },
  emptyTitle: {
    color: colors.text.primary,
    fontSize: 17,
    fontWeight: '800',
  },
  eyebrow: {
    color: colors.neutral[200],
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  feedbackBox: {
    backgroundColor: colors.danger.background,
    borderColor: colors.danger.border,
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  feedbackText: {
    color: colors.danger.textStrong,
    fontSize: 13,
    lineHeight: 18,
  },
  feedbackTitle: {
    color: colors.danger.text,
    fontSize: 15,
    fontWeight: '800',
  },
  filterRow: {
    gap: 8,
    paddingRight: 16,
  },
  filterActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  filterGroup: {
    gap: 8,
  },
  filterGroupHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  filterLabel: {
    color: colors.text.tertiary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  filtersPanel: {
    backgroundColor: colors.surface.card,
    borderColor: colors.border.default,
    borderRadius: 8,
    borderWidth: 1,
    elevation: 1,
    gap: 14,
    padding: 14,
    shadowColor: colors.shadow.card,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  filterSkeletonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  header: {
    gap: 14,
    marginBottom: 14,
  },
  listIntro: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  offlineBanner: {
    backgroundColor: colors.brand.subtle,
    borderColor: colors.brand.link,
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  offlineBannerText: {
    color: colors.brand.linkStrong,
    fontSize: 13,
    lineHeight: 18,
  },
  offlineBannerTitle: {
    color: colors.brand.linkStrong,
    fontSize: 14,
    fontWeight: '900',
  },
  overviewPanel: {
    backgroundColor: colors.surface.hero,
    borderRadius: 8,
    gap: 18,
    padding: 18,
  },
  panelHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  paginationFooter: {
    gap: 12,
    paddingTop: 16,
  },
  paginationText: {
    color: colors.text.tertiary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  resultLabel: {
    color: colors.text.tertiary,
    fontSize: 13,
    fontWeight: '700',
    flexShrink: 1,
    textAlign: 'right',
  },
  safeArea: {
    backgroundColor: colors.surface.app,
    flex: 1,
  },
  separator: {
    height: 12,
  },
  sectionTitle: {
    color: colors.text.primary,
    fontSize: 16,
    fontWeight: '900',
  },
  summaryBox: {
    backgroundColor: colors.surface.overlay,
    borderColor: colors.border.onDark,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    minWidth: 88,
    minHeight: 74,
    padding: 12,
  },
  summaryBoxWide: {
    backgroundColor: colors.surface.overlay,
    borderColor: colors.border.onDark,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1.4,
    gap: 2,
    minWidth: 112,
    minHeight: 74,
    padding: 12,
  },
  summaryLabel: {
    color: colors.neutral[200],
    fontSize: 12,
    fontWeight: '800',
    marginTop: 3,
    textTransform: 'uppercase',
  },
  summaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  summaryValue: {
    color: colors.text.inverted,
    fontSize: 19,
    fontWeight: '900',
  },
  skeletonList: {
    gap: 12,
  },
  taskSkeletonCard: {
    backgroundColor: colors.surface.card,
    borderColor: colors.border.default,
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  taskSkeletonFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  taskSkeletonHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  title: {
    color: colors.text.inverted,
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 36,
  },
  titleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  titleStack: {
    flex: 1,
  },
});
