// Generated by scripts/apply-env.js. Do not edit manually.
export const environment = {
  name: "production",
  apiBaseURL: {
    ios: "https://management-api-y4gi.onrender.com/api",
    android: "https://management-api-y4gi.onrender.com/api",
    default: "https://management-api-y4gi.onrender.com/api",
  },
} as const;
