// Generated by scripts/apply-env.js. Do not edit manually.
export const environment = {
  name: 'local',
  apiBaseURL: {
    ios: 'http://localhost:3000/api',
    android: 'http://10.0.2.2:3000/api',
    default: 'http://localhost:3000/api',
  },
} as const;
