const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const requestedEnv = process.argv[2] || process.env.APP_ENV || 'local';
const envName = requestedEnv === 'prod' ? 'production' : requestedEnv;
const allowedEnvs = new Set(['local', 'production']);

if (!allowedEnvs.has(envName)) {
  throw new Error(`Invalid app env "${requestedEnv}". Use "local" or "production".`);
}

const envPath = path.join(root, `.env.${envName}`);

if (!fs.existsSync(envPath)) {
  throw new Error(`Missing env file: ${envPath}`);
}

function parseEnvFile(filePath) {
  return fs
    .readFileSync(filePath, 'utf8')
    .split(/\r?\n/)
    .reduce((acc, line) => {
      const trimmed = line.trim();

      if (!trimmed || trimmed.startsWith('#')) {
        return acc;
      }

      const separatorIndex = trimmed.indexOf('=');

      if (separatorIndex === -1) {
        return acc;
      }

      const key = trimmed.slice(0, separatorIndex).trim();
      const rawValue = trimmed.slice(separatorIndex + 1).trim();
      acc[key] = rawValue.replace(/^["']|["']$/g, '');

      return acc;
    }, {});
}

const env = parseEnvFile(envPath);
const iosApiBaseURL = env.IOS_API_BASE_URL;
const androidApiBaseURL = env.ANDROID_API_BASE_URL;
const defaultApiBaseURL = env.DEFAULT_API_BASE_URL;
const requiredValues = { iosApiBaseURL, androidApiBaseURL, defaultApiBaseURL };

for (const [key, value] of Object.entries(requiredValues)) {
  if (!value) {
    throw new Error(`Missing ${key} in ${envPath}`);
  }

  if (value.includes('REPLACE_WITH_RENDER_SERVICE_URL')) {
    throw new Error(
      `Replace the production API URL in ${envPath} before building production.`,
    );
  }
}

const output = `// Generated by scripts/apply-env.js. Do not edit manually.
export const environment = {
  name: ${JSON.stringify(env.APP_ENV || envName)},
  apiBaseURL: {
    ios: ${JSON.stringify(iosApiBaseURL)},
    android: ${JSON.stringify(androidApiBaseURL)},
    default: ${JSON.stringify(defaultApiBaseURL)},
  },
} as const;
`;

const outputDir = path.join(root, 'src/config');
fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(path.join(outputDir, 'environment.ts'), output);

console.log(`Applied ${envName} env from ${path.relative(root, envPath)}`);
